networks:
  authentik_internal:
    name: authentik_internal
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.28.0.0/29
    enable_ipv6: false

  # docker_proxy_internal:
  #   name: docker_proxy
  #   driver: bridge
  #   internal: true
  #   ipam:
  #     config:
  #       - subnet: 172.29.0.0/29
  #   enable_ipv6: false