# Static configuration
api:
  dashboard: true
  insecure: false  # Disable this when adding security later


entryPoints:
  web:
    address: ":80"
    forwardedHeaders:
      trustedIPs: &trustedIps
        # start of Clouflare public IP list for HTTP requests, remove this if you don't use it; https://www.cloudflare.com/de-de/ips/
        - 173.245.48.0/20
        - 103.22.200.0/22
        - 103.21.244.0/22
        - 103.31.4.0/22
        - 141.101.64.0/18
        - 108.162.192.0/18
        - 190.93.240.0/20
        - 188.114.96.0/20
        - 197.234.240.0/22
        - 198.41.128.0/17
        - 162.158.0.0/15
        - 104.16.0.0/13
        - 104.24.0.0/14
        - 172.64.0.0/13
        - 131.0.72.0/22
        - 2400:cb00::/32
        - 2606:4700::/32
        - 2803:f800::/32
        - 2405:b500::/32
        - 2405:8100::/32
        - 2a06:98c0::/29
        - 2c0f:f248::/32
        # end of Cloudlare public IP list
  websecure:
    address: ":443"
    forwardedHeaders:
      # reuse list of Cloudflare Trusted IP's above for HTTPS requests
      trustedIPs: *trustedIps

    http:
      tls: {}
  metrics:
    address: :8082
  

metrics:
  prometheus:
    addEntryPointsLabels: true
    addRoutersLabels: true
    entryPoint: metrics

providers:
  docker:
    exposedByDefault: false
    network: "traefik-net"
  file:
    directory: /dynamic
    watch: true

# log:
#   level: INFO

accessLog: {}  # Enable access logs

# experimental:
#   plugins:
#     cloudflarewarp:
#       moduleName: github.com/BetterCorp/cloudflarewarp
#       version: v1.3.3